### ISSUE TITLE
编译Android系统时，提示找不到 kernel/config

### ISSUE THREAD

**Issue by dongfengweixiao** [radxa/manifests#1]
使用 docker 下的 Ubuntu：16.04 作为编译环境编译编译日志如下：

make -j1 showcommands
12:46:07 Took 30ms to start up.
12:46:07 Starting build with args: []
12:46:07 Environment: [ANDROID_DEV_SCRIPTS=/aosp/development/scripts:/aosp/prebuilts/devtools/tools:/aosp/external/selinux/prebuilts/bin:/aosp/prebuilts/misc/linux-x86/dtc:/aosp/prebuilts/misc/linux-x86/libufdt HOSTNAME=d6f7741b625b ANDROID_PRE_BUILD_PATHS=/aosp/prebuilts/jdk/jdk9/linux-x86/bin: TRACE_BEGIN_SOONG=1575809167614042566 ANDROID_BUILD_TOP=/aosp ANDROID_PRODUCT_OUT=/aosp/out/target/product/rk3399 TERM=xterm SHELL=/bin/sh ANDROID_TARGET_OUT_TESTCASES=/aosp/out/target/product/rk3399/testcases OLDPWD=/aosp OUT=/aosp/out/target/product/rk3399 TARGET_BUILD_VARIANT=userdebug USER=aosp LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: ASAN_OPTIONS=detect_leaks=0 CCACHE_DIR=/tmp/ccache SUDO_USER=root SUDO_UID=0 BUILD_ENV_SEQUENCE_NUMBER=13 ANDROID_BUILD_PATHS=/aosp/out/soong/host/linux-x86/bin:/aosp/out/host/linux-x86/bin:/aosp/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:/aosp/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:/aosp/development/scripts:/aosp/prebuilts/devtools/tools:/aosp/external/selinux/prebuilts/bin:/aosp/prebuilts/misc/linux-x86/dtc:/aosp/prebuilts/misc/linux-x86/libufdt:/aosp/prebuilts/android-emulator/linux-x86_64: ANDROID_HOST_OUT_TESTCASES=/aosp/out/host/linux-x86/testcases TARGET_BOARD_PLATFORM_GPU=mali-t860 USERNAME=aosp TOP=/aosp TARGET_BUILD_APPS= TARGET_BUILD_TYPE=release PWD=/aosp ANDROID_TOOLCHAIN=/aosp/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin ANDROID_TOOLCHAIN_2ND_ARCH=/aosp/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01 SHLVL=1 HOME=/home/aosp SUDO_COMMAND=/bin/bash ORIGINAL_PWD=/aosp LOGNAME=aosp PYTHONPATH=/aosp/development/python-packages:/aosp/development/python-packages: ANDROID_EMULATOR_PREBUILTS=/aosp/prebuilts/android-emulator/linux-x86_64 TARGET_GCC_VERSION=4.9 USE_CCACHE=1 LESSOPEN=| /usr/bin/lesspipe %s SUDO_GID=0 TARGET_PRODUCT=rk3399 ANDROID_HOST_OUT=/aosp/out/host/linux-x86 LESSCLOSE=/usr/bin/lesspipe %s %s OUT_DIR=out PYTHONDONTWRITEBYTECODE=1 LANG=C.UTF-8 JAVA_HOME=/aosp/prebuilts/jdk/jdk9/linux-x86 ANDROID_JAVA_HOME=prebuilts/jdk/jdk9/linux-x86 ANDROID_JAVA8_HOME=prebuilts/jdk/jdk8/linux-x86 ANDROID_JAVA9_HOME=prebuilts/jdk/jdk9/linux-x86 PATH=/aosp/prebuilts/jdk/jdk9/linux-x86/bin:/aosp/prebuilts/jdk/jdk9/linux-x86/bin:/aosp/out/soong/host/linux-x86/bin:/aosp/out/host/linux-x86/bin:/aosp/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:/aosp/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:/aosp/development/scripts:/aosp/prebuilts/devtools/tools:/aosp/external/selinux/prebuilts/bin:/aosp/prebuilts/misc/linux-x86/dtc:/aosp/prebuilts/misc/linux-x86/libufdt:/aosp/prebuilts/android-emulator/linux-x86_64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin BUILD_DATETIME_FILE=out/build_date.txt]
12:46:07 prebuilts/build-tools/linux-x86/bin/ckati [prebuilts/build-tools/linux-x86/bin/ckati -f build/make/core/config.mk --color_warnings --kati_stats dump-many-vars MAKECMDGOALS=]
12:46:07 *kati*: Stack size: 8376320 bytes
12:46:08 *kati*: eval time: 0.440468
12:46:08 *kati*: 10 explicit rules
12:46:08 *kati*: 0 implicit rules
12:46:08 *kati*: 1 suffix rules
12:46:08 *kati*: make dep (populate): 0.000024
12:46:08 *kati*: make dep (build): 0.000003
12:46:08 *kati*: make dep time: 0.000035
12:46:08 *kati*: exec time: 0.001430
12:46:08 *kati*: Max stack use: 20400 bytes at build/target/product/embedded.mk:118
12:46:08 *kati*: parse eval time: 0.040987 / 59970
12:46:08 *kati*: parse file time: 0.005259 / 111
12:46:08 *kati*: func shell time: 0.308454 / 42
12:46:08 *kati*:  0.036 python device/rockchip/common/auto_generator.py device/rockchip/rk3399 preinstall_del bundled_uninstall_back-app
12:46:08 *kati*:  0.031 python device/rockchip/common/auto_generator.py device/rockchip/rk3399 preinstall bundled_persist-app
12:46:08 *kati*:  0.029 test -d device && find -L device -maxdepth 6 -name .git -prune -o -name AndroidProducts.mk -print
12:46:08 *kati*:  0.017 python device/rockchip/common/auto_generator.py device/rockchip/rk3399 preinstall_del_forever bundled_uninstall_gone-app
12:46:08 *kati*:  0.015 python device/rockchip/common/get_partition_size.py device/rockchip/rk3399/parameter.txt system
12:46:08 *kati*:  0.014 test -d vendor && find -L vendor -maxdepth 6 -name .git -prune -o -name AndroidProducts.mk -print
12:46:08 *kati*:  0.014 python device/rockchip/common/get_partition_size.py device/rockchip/rk3399/parameter.txt recovery
12:46:08 *kati*:  0.014 python device/rockchip/common/get_partition_size.py device/rockchip/rk3399/parameter.txt boot
12:46:08 *kati*:  0.014 python device/rockchip/common/get_partition_size.py device/rockchip/rk3399/parameter.txt vendor
12:46:08 *kati*:  0.014 python device/rockchip/common/get_partition_size.py device/rockchip/rk3399/parameter.txt oem
12:46:08 *kati*: func wildcard time: 0.000890 / 123
12:46:08 *kati*: func sort time: 0.001738 / 4061
12:46:08 *kati*: 5807 symbols
12:46:08 NINJA_GOALS droid
12:46:08 KATI_GOALS
12:46:08 TARGET_DEVICE rk3399
12:46:08 TARGET_PRODUCT rk3399
12:46:08 TARGET_BUILD_VARIANT userdebug
12:46:08 TARGET_BUILD_APPS
12:46:08 CC_WRAPPER prebuilts/misc/linux-x86/ccache/ccache
12:46:08 CXX_WRAPPER prebuilts/misc/linux-x86/ccache/ccache
12:46:08 JAVAC_WRAPPER
12:46:08 CCACHE_COMPILERCHECK content
12:46:08 CCACHE_SLOPPINESS time_macros,include_file_mtime,file_macro
12:46:08 CCACHE_BASEDIR /
12:46:08 CCACHE_CPP2 true
12:46:08 PLATFORM_VERSION_CODENAME REL
12:46:08 PLATFORM_VERSION 9
12:46:08 TARGET_PRODUCT rk3399
12:46:08 TARGET_BUILD_VARIANT userdebug
12:46:08 TARGET_BUILD_TYPE release
12:46:08 TARGET_BUILD_APPS
12:46:08 TARGET_ARCH arm64
12:46:08 TARGET_ARCH_VARIANT armv8-a
12:46:08 TARGET_CPU_VARIANT cortex-a53
12:46:08 TARGET_2ND_ARCH arm
12:46:08 TARGET_2ND_ARCH_VARIANT armv7-a-neon
12:46:08 TARGET_2ND_CPU_VARIANT cortex-a15
12:46:08 HOST_ARCH x86_64
12:46:08 HOST_2ND_ARCH x86
12:46:08 HOST_OS linux
12:46:08 HOST_OS_EXTRA Linux-5.4.2-arch1-1-x86_64-Ubuntu-16.04.6-LTS
12:46:08 HOST_CROSS_OS windows
12:46:08 HOST_CROSS_ARCH x86
12:46:08 HOST_CROSS_2ND_ARCH x86_64
12:46:08 HOST_BUILD_TYPE release
12:46:08 BUILD_ID PQ3B.190801.002
12:46:08 OUT_DIR out
12:46:08 AUX_OS_VARIANT_LIST
12:46:08 TARGET_BUILD_PDK
12:46:08 PDK_FUSION_PLATFORM_ZIP
12:46:08 PRODUCT_SOONG_NAMESPACES
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=rk3399
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a15
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.2-arch1-1-x86_64-Ubuntu-16.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3B.190801.002
OUT_DIR=out
============================================
12:46:08 build/blueprint/bootstrap.bash [build/blueprint/bootstrap.bash -t]
12:46:08 out/soong/.bootstrap/bin/soong_env [out/soong/.bootstrap/bin/soong_env out/soong/.soong.environment]
12:46:08 prebuilts/build-tools/linux-x86/bin/ninja [prebuilts/build-tools/linux-x86/bin/ninja -d keepdepfile -w dupbuild=err -j 1 -f out/soong/.minibootstrap/build.ninja -v]
ninja: no work to do.
12:46:08 Ninja log not modified, not importing any entries.
12:46:08 prebuilts/build-tools/linux-x86/bin/ninja [prebuilts/build-tools/linux-x86/bin/ninja -d keepdepfile -w dupbuild=err -j 1 -f out/soong/.bootstrap/build.ninja -v]
ninja: no work to do.
12:46:08 Ninja log not modified, not importing any entries.
12:46:08 prebuilts/build-tools/linux-x86/bin/ckati [prebuilts/build-tools/linux-x86/bin/ckati --ninja --ninja_dir=out --ninja_suffix=-rk3399-cleanspec --regen --detect_android_echo --color_warnings --gen_all_targets --werror_find_emulator --use_find_emulator -f build/make/core/cleanbuild.mk BUILDING_WITH_NINJA=true SOONG_MAKEVARS_MK=out/soong/make_vars-rk3399.mk]
device/rockchip/rk3399/preinstall_del/preinstall.mk was modified, regenerating...
12:46:09 prebuilts/build-tools/linux-x86/bin/ckati [prebuilts/build-tools/linux-x86/bin/ckati --ninja --ninja_dir=out --ninja_suffix=-rk3399 --regen --ignore_optional_include=out/%.P --detect_android_echo --color_warnings --gen_all_targets --werror_find_emulator --kati_stats -f build/make/core/main.mk --use_find_emulator BUILDING_WITH_NINJA=true SOONG_ANDROID_MK=out/soong/Android-rk3399.mk SOONG_MAKEVARS_MK=out/soong/make_vars-rk3399.mk]
out/build-rk3399.ninja is missing, regenerating...
12:46:09 *kati*: regen check time: 0.000038
12:46:09 *kati*: Stack size: 8380416 bytes
Traceback (most recent call last):
  File "/aosp/.repo/repo/main.py", line 530, in <module>
    _Main(sys.argv[1:])
  File "/aosp/.repo/repo/main.py", line 505, in _Main
    result = run()
  File "/aosp/.repo/repo/main.py", line 498, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/aosp/.repo/repo/main.py", line 201, in _Run
    result = cmd.Execute(copts, cargs)
  File "/aosp/.repo/repo/subcmds/manifest.py", line 80, in Execute
    self._Output(opt)
  File "/aosp/.repo/repo/subcmds/manifest.py", line 70, in _Output
    peg_rev_upstream = opt.peg_rev_upstream)
  File "/aosp/.repo/repo/manifest_xml.py", line 365, in Save
    output_projects(None, root, list(sorted(projects)))
  File "/aosp/.repo/repo/manifest_xml.py", line 275, in output_projects
    output_project(parent, parent_node, project)
  File "/aosp/.repo/repo/manifest_xml.py", line 302, in output_project
    value = p.work_git.rev_parse(HEAD + '^0')
  File "/aosp/.repo/repo/project.py", line 3114, in runner
    capture_stderr=True)
  File "/aosp/.repo/repo/git_command.py", line 294, in __init__
    raise GitError('%s: %s' % (command[1], e))
error.GitError: rev-parse: [Errno 2] No such file or directory: '/aosp/kernel/configs'
12:46:11 *kati*: 889503 find nodes
12:46:11 *kati*: init find emulator time: 1.171705
[4/1015] including bootable/recovery/Android.mk ...
/bin/bash: line 0: test: -ge: unary operator expected
/bin/bash: line 0: test: -ge: unary operator expected
[343/1015] including hardware/rockchip/omx_il/Android.mk ...
tools/hooks .git/hooks
[345/1015] including hardware/rockchip/sensor/Android.mk ...
YD>>PLATFORM_VERSION=9
YD>>ANDRIOD VERSION=9.9
YD>>VERSION_L=, VERSION_KK=
YD>>LOCAL_MODULE=sensors.rk30board
YD>>LOCAL_MODULE=sensors.rk30board, LOCAL_SRC_FILES=sensors_mpl.cpp SamsungSensorBase.cpp LightSensor.cpp ProximitySensor.cpp, LOCAL_SHARED_LIBRARIES=libinvensense_hal libcutils libutils libdl liblog libmllite libhardware
[512/1015] including system/core/Android.mk ...
sed: can't read development/sdk/plat_tools_source.prop_template: No such file or directory
sed: can't read development/sdk/plat_tools_source.prop_template: No such file or directory
[524/1015] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[1015/1015] including vendor/rockchip/common/vpu/Android.mk ...
test/vts/tools/build/tasks/vts_package.mk:141: error: FindEmulator: cd: kernel/configs: No such file or directory
12:47:03 ckati failed with: exit status 1

**Comment by Ahren-Li** [comment]
你是不是把kernel/configs 给删掉了？

**Comment by Ahren-Li** [comment]
repo sync -c -d --no-tags kernel/configs

**Comment by dongfengweixiao** [comment]
已解决，谢谢。
