### ISSUE TITLE
android 11: multitouch usb hid not rotating with screen

### ISSUE THREAD

**Issue by joejulian** [radxa/manifests#13]
When the screen is rotated, the multitouch interface does not rotate with it.

Regardless of which method is used to rotate the screen, the touch remains in upright landscape orientation. This is the uevent data for the hid device. Let me know if there's any additional information you need.

```
PRODUCT=3/222a/1/110
NAME=“ILITEK ILITEK-TP”
PHYS=“usb-xhci-hcd.1.auto-1/input0”
UNIQ=""
PROP=2
EV=1b
KEY=400 0 0 0 0 0
ABS=260800000000003
MSC=20
MODALIAS=input:b0003v222Ap0001e0110-e0,1,3,4,k14A,ra0,1,2F,35,36,39,m5,lsfw
```

**Comment by joejulian** [comment]
Thanks for the help.

**Comment by aroeiraio** [comment]
Hello @joejulian, can you share the solution for it?

**Comment by joejulian** [comment]
I gave up on ever getting help with this and having an open issue on my dashboard was annoying me. It's not solved.
