### ISSUE TITLE
Can not compile Android_rk12.1 Rock 5B

### ISSUE THREAD

**Issue by abrilevskiy** [radxa/manifests#39]
`Runtime aborting...
All threads:
DALVIK THREADS (1):
"main" prio=5 tid=1 Runnable (still starting up)
  | group="" sCount=0 ucsCount=0 flags=0 obj=(nil) self=0x555556ec7760
  | sysTid=28570 nice=0 cgrp=default sched=0/0 handle=0x7ffffedf0740
  | state=R schedstat=( 190898998 68334 22 ) utm=16 stm=2 core=3 HZ=100
  | stack=0x5554ff800000-0x5554ff802000 stackSize=8192KB
  | held mutexes= "abort lock" "mutator lock"(shared held)
  native: #00 pc 0000000000da4aa8  /home/android12-docker/rock-android12/out/soong/host/linux-x86/bin/dex2oatd64 (UnwindStackCurrent::UnwindFromContext(unsigned long, void*)+88)
  (no managed stack frames)

dex2oatd E 04-24 18:08:16 28570 28570 thread-inl.h:158] holding "abort lock" at point where thread suspension is expected
Aborting thread:
"main" prio=5 tid=1 Runnable (still starting up)
  | group="" sCount=0 ucsCount=0 flags=0 obj=(nil) self=0x555556ec7760
  | sysTid=28570 nice=0 cgrp=default sched=0/0 handle=0x7ffffedf0740
  | state=R schedstat=( 268896750 83583 41 ) utm=24 stm=2 core=0 HZ=100
  | stack=0x5554ff800000-0x5554ff802000 stackSize=8192KB
  | held mutexes= "abort lock" "mutator lock"(shared held)
  native: #00 pc 0000000000da4aa8  /home/android12-docker/rock-android12/out/soong/host/linux-x86/bin/dex2oatd64 (UnwindStackCurrent::UnwindFromContext(unsigned long, void*)+88)
  native:   std::__1::__compressed_pair_elem<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, 0, false>::__compressed_pair_elem()
  native:    external/libcxx/include/memory:2140
  native:   std::__1::__compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__rep, std::__1::allocator<char> >::__compressed_pair<true, void>()
  native:    external/libcxx/include/memory:2234
  native:   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<decltype(nullptr)>(char const*)
  native:    external/libcxx/include/string:820
  native:   UnwindStackCurrent::UnwindFromContext(unsigned long, void*)
  native:    system/unwinding/libbacktrace/UnwindStack.cpp:169
  (no managed stack frames)
Aborted
ERROR: Dex2oat failed to compile a boot image.It is likely that the boot classpath is inconsistent.Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS="--runtime-arg -verbose:verifier" to see verification errors.
18:08:26 ninja failed with: exit status 1`

`dex2oatd I 04-24 16:44:59 26806 26806 method_verifier.cc:5171] Soft verification failures in java.lang.String java.net.IDN.toASCII(java.lang.String, int)
dex2oatd I 04-24 16:44:59 26806 26806 method_verifier.cc:5171] java.lang.String java.net.IDN.toASCII(java.lang.String, int): [0x0] (possibly) illegal class access: 'Precise Reference: java.net.IDN' -> 'Unresolved Reference: com.android.icu.text.ExtendedIDNA'
dex2oatd I 04-24 16:44:59 26806 26806 method_verifier.cc:5171] Soft verification failures in void java.text.Bidi.<init>(java.lang.String, int)
dex2oatd I 04-24 16:44:59 26806 26806 method_verifier.cc:5171] void java.text.Bidi.<init>(java.lang.String, int): [0x5] (possibly) illegal class access: 'Precise Reference: java.text.Bidi' -> 'Unresolved Reference: android.icu.text.Bidi'
dex2oatd I 04-24 16:44:59 26806 26806 method_verifier.cc:5171] void java.text.Bidi.<init>(java.lang.String, int): [0x17] (possibly) illegal class access: 'Precise Reference: java.text.Bidi' -> 'Unresolved Reference: android.icu.text.Bidi'
...`

**Comment by peterwang2050** [comment]
Maybe it's a compile env issue.  such as memory size is not large enough 

https://blog.csdn.net/zwx168238/article/details/87805894

**Comment by abrilevskiy** [comment]
I was able to build working image in Ubuntu 22.04
