### ISSUE TITLE
 No configuration exists for this target on this architecture.

### ISSUE THREAD

**Issue by lberezinski** [radxa/manifests#50]
Hi all,

I'm following this guide https://wiki.radxa.com/Rock5/guide/android12

To build android 12 on my rock5a using Ubuntu 16 64bit. When It gets to build the kernel I get the following error.

scripts/kconfig/Makefile:93: *** No configuration exists for this target on this architecture.  Stop.
Makefile:627: recipe for target 'intel_iwlwifi.config' failed
make[1]: *** [intel_iwlwifi.config] Error 2
Makefile:350: recipe for target '__build_one_by_one' failed
make: *** [__build_one_by_one] Error 2
#### failed to build some targets (13 seconds) ####
Build kernel failed!

Any help.will be appreciated!

**Comment by lberezinski** [comment]
Started from scratch and this time.it worked.

**Comment by lberezinski** [comment]
See above

**Comment by adi6409** [comment]
Encountering the same issue, running everything again did not solve it for me. Did you also delete the entire repo and download everything again?
